[package]
name = "diman"
version = "0.1.0"
edition = "2021"

[features]
si = []
mpi = ["dep:once_cell", "dep:mpi"]
hdf5 = ["dep:hdf5"]
rand = ["dep:rand"]
serde = ["dep:serde"]
default = ["si"]

[lib]

[dependencies]
paste = "1.0.8"
num-traits = "0.2.15"
glam = { version = "0.21.3" }
rand = { version = "0.8.5", optional = true }
serde = {version = "1.0.143", features = ["derive"], optional = true }
hdf5 = {version = "0.8.1", optional = true }
mpi = { version = "0.6", default-features = false, features = ["derive"], optional = true }
once_cell = { version = "1.13.0", optional = true }

[dev-dependencies]
serde_yaml = "0.9.9"
lazy_static = "1.4.0"