[package]
name = "diman"
version = "0.1.0"
edition = "2021"

[features]
glam = ["dep:glam"]
mpi = ["dep:once_cell", "dep:mpi"]
hdf5 = ["dep:hdf5"]
rand = ["dep:rand"]
serde = ["dep:serde"]
default-2d = []
default-3d = []
default-f32 = []
default-f64 = []
default = []

[lib]

[dependencies]
paste = "1.0.8"
glam = { version = "0.21.3", optional = true }
rand = { version = "0.8.5", optional = true }
serde = {version = "1.0.143", features = ["derive"], optional = true }
hdf5 = { rev = "7eb87b800e2806fcd416e5f76dc16998bf311525", git = "https://github.com/aldanor/hdf5-rust", optional = true}
mpi = { version = "0.6", default-features = false, features = ["derive"], optional = true }
once_cell = { version = "1.13.0", optional = true }
derive_dimension = { path = "crates/derive_dimension" }
unit_system = { path = "crates/unit_system" }

[dev-dependencies]
serde_yaml = "0.9.9"
lazy_static = "1.4.0"