#!/bin/bash

diff=$(cargo fmt -- --check)
result=$?

if [[ ${result} -ne 0 ]] ; then
    cat <<\EOF
There are some code style issues, run `cargo fmt` first.
EOF
    exit 1
fi

for float in default-f32, "" ; do
    for dim in default-2d, ""; do
        echo "$float" "$dim"
        echo cargo test --no-default-features --features "si,${dim}${float},mpi,rand,serde,hdf5"
        if ! cargo test --no-default-features --features "si,${dim}${float},mpi,rand,serde,hdf5"
        then
            echo "There are some test issues."
            exit 1
        fi
    done
done

exit 0
