#!/bin/bash

diff=$(cargo fmt -- --check)
result=$?

if [[ ${result} -ne 0 ]] ; then
    cat <<\EOF
There are some code style issues, run `cargo fmt` first.
EOF
fi


if ! cargo test --all-features
then
    echo "test failed"
    exit 1
fi

if ! cargo test --manifest-path crates/unit_system/Cargo.toml --all-features
then
    echo "unit_system test failed"
    exit 1
fi

diff=$(cargo fmt -- --check)
result=$?

if [[ ${result} -ne 0 ]] ; then
    cat <<\EOF
There are some code style issues, run `cargo fmt` first.
EOF
    exit 1
fi
